name: Docker Image CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Harbor
        uses: docker/login-action@v1
        with:
          registry: harbor.kway.club
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            harbor.kway.club/library/chatgpt-discord-bot:${{ github.run_number }}
            harbor.kway.club/library/chatgpt-discord-bot:latest
          cache-from: type=registry,ref=harbor.kway.club/library/chatgpt-discord-bot:cache
          cache-to: type=inline